name: ci

on:
  push:
    branches:
      - main
      - develop
      - 'issues/*'
  pull_request:
    branches:
      - main
      - develop
      - 'issues/*'

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test
      - name: Linter check
        run: yarn lint
      - name: Test build
        run: yarn build
      - name: Check for security vulnerabilities
        run: yarn audit
